// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: envoy/extensions/bootstrap/reverse_tunnel/upstream_socket_interface/v3/upstream_reverse_connection_socket_interface.proto

package upstream_socket_interfacev3

import (
	_ "github.com/Lingbo-Huang/my-epp/envoy/api/udpa/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for the upstream reverse connection socket interface.
type UpstreamReverseConnectionSocketInterface struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stat prefix to be used for upstream reverse connection socket interface stats.
	StatPrefix    string `protobuf:"bytes,1,opt,name=stat_prefix,json=statPrefix,proto3" json:"stat_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamReverseConnectionSocketInterface) Reset() {
	*x = UpstreamReverseConnectionSocketInterface{}
	mi := &file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamReverseConnectionSocketInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamReverseConnectionSocketInterface) ProtoMessage() {}

func (x *UpstreamReverseConnectionSocketInterface) ProtoReflect() protoreflect.Message {
	mi := &file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamReverseConnectionSocketInterface.ProtoReflect.Descriptor instead.
func (*UpstreamReverseConnectionSocketInterface) Descriptor() ([]byte, []int) {
	return file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDescGZIP(), []int{0}
}

func (x *UpstreamReverseConnectionSocketInterface) GetStatPrefix() string {
	if x != nil {
		return x.StatPrefix
	}
	return ""
}

var File_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto protoreflect.FileDescriptor

const file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDesc = "" +
	"\n" +
	"yenvoy/extensions/bootstrap/reverse_tunnel/upstream_socket_interface/v3/upstream_reverse_connection_socket_interface.proto\x12Fenvoy.extensions.bootstrap.reverse_tunnel.upstream_socket_interface.v3\x1a\x1dudpa/annotations/status.proto\"K\n" +
	"(UpstreamReverseConnectionSocketInterface\x12\x1f\n" +
	"\vstat_prefix\x18\x01 \x01(\tR\n" +
	"statPrefixB\x9b\x02\xba\x80\xc8\xd1\x06\x02\x10\x02\n" +
	"Tio.envoyproxy.envoy.extensions.bootstrap.reverse_tunnel.upstream_socket_interface.v3B-UpstreamReverseConnectionSocketInterfaceProtoP\x01Z\x89\x01github.com/envoyproxy/go-control-plane/envoy/extensions/bootstrap/reverse_tunnel/upstream_socket_interface/v3;upstream_socket_interfacev3b\x06proto3"

var (
	file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDescOnce sync.Once
	file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDescData []byte
)

func file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDescGZIP() []byte {
	file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDescOnce.Do(func() {
		file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDesc), len(file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDesc)))
	})
	return file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDescData
}

var file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_goTypes = []any{
	(*UpstreamReverseConnectionSocketInterface)(nil), // 0: envoy.extensions.bootstrap.reverse_tunnel.upstream_socket_interface.v3.UpstreamReverseConnectionSocketInterface
}
var file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_init()
}
func file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_init() {
	if File_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDesc), len(file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_goTypes,
		DependencyIndexes: file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_depIdxs,
		MessageInfos:      file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_msgTypes,
	}.Build()
	File_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto = out.File
	file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_goTypes = nil
	file_envoy_extensions_bootstrap_reverse_tunnel_upstream_socket_interface_v3_upstream_reverse_connection_socket_interface_proto_depIdxs = nil
}
